### ISSUE TITLE
Website Favicon change

### ISSUE THREAD

**Issue by alee020304** [jinleevv/akcse#30]
Recommendation to have non-png favicon, as the AKCSE logo is hidden in Chrome dark-mode (hint: check out design items in the AKCSE drive)
![image](https://github.com/user-attachments/assets/49c92827-627e-4511-8804-1b49d82f4e31)
This is how it looks when it is not clicked on
![image](https://github.com/user-attachments/assets/7ed5b447-521e-4f6c-8e2c-ef1c21b810c8)

**Comment by jinleevv** [comment]
done
